# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Nuget Restore'
  inputs: 
    command: 'restore'
    
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs: 
    command: 'build'
    arguments: '-o --configuration $(BuildConfiguration) /p:Version=$(GitVersion.NuGetVersion)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    nobuild: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GitVersion.NuGetVersion'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'c2e0467b-2b81-4f61-ba30-2a195a26f9b8/9aed2e3b-6ba8-4b6c-a48a-7dcf2565d087'